### ISSUE TITLE
A simple AttributeError

### ISSUE THREAD

**Issue by ffiore** [ioggstream/iposonic#10]
INFO:werkzeug:127.0.0.1 - - [11/Oct/2012 10:35:57] "GET /rest/getCoverArt.view?v=9.0.0&c=MiniSub&f=jsonp&size=50&id=-1341576754 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1701, in **call**
    return self.wsgi_app(environ, start_response)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/goofy/Projects/iposonic/view_media.py", line 302, in get_cover_art_view
    cover_art_path = get_cover_art_file(eid)
  File "/home/goofy/Projects/iposonic/view_media.py", line 191, in tmp
    cache2[eid] = (f(eid, nocache=nocache), time.time())
  File "/home/goofy/Projects/iposonic/view_media.py", line 238, in get_cover_art_file
    "/", app.iposonic.cache_dir, MediaManager.cover_art_uuid(info))
  File "/usr/lib64/python2.7/posixpath.py", line 66, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'

**Comment by ioggstream** [comment]
the error is thrown by  MediaManager.cover_art_uuid(info))

it generates an uuid from (artist, album) contained in info.

In your file one of those fields is null.

You're welcome to add some checks in  get_coverart_uuid() or to provide infos in your file :P

Peace,
R.
